name: flutterapp
description: A new Flutter project.

environment:
  sdk: "^3.7.2"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  webview_flutter_android: ^4.4.1
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/dashboard/mining.html
    - assets/dashboard/logistic.html
    - assets/dashboard/pipeline.html
